/* eslint-disable sort-imports */
import * as core from '@actions/core'
import axios, {AxiosRequestConfig} from 'axios'
import { createBrotliCompress } from 'zlib'
import {
  GetRunResponse,
  Run,
  RunResponseInterface
} from './interfaces/runInterface'

function getRunName(): string {
  const date = new Date()
  return `Automated Test Run ${date.getDay()}/${date.getMonth()}/${date.getFullYear()}`
}

function getTestRailConfg(path: string, method?: string): AxiosRequestConfig {
  const host = core.getInput('testrail_host')
  const username = core.getInput('testrail_username')
  const password = core.getInput('testrail_password')
  const config: AxiosRequestConfig = {
    method: method || 'GET',
    headers: {
      'Content-Type': 'application/json'
    },
    url: `${host}/${path}`,
    withCredentials: true,
    auth: {
      username,
      password
    }
  }
  return config
}

export async function getOrCreateRunID(): Promise<Run | undefined> {
  try {
    const projectId = core.getInput('testrail_projectid')
    const response = await getRuns(projectId)
    core.debug('GET THE LIST OF RUNs')
    core.debug(JSON.stringify(response))
    const runName = getRunName()
    core.debug('Create the run name')
    core.debug(runName)
    let match = (response.runs || []).find(
      runInfo => runInfo.name.toLowerCase() === runName
    )
    core.debug('Creck if exist')
    core.debug(JSON.stringify(match))
    if (!match) {
      core.debug('Not match found')
      const suiteId = core.getInput('testrail_suidId')
      core.debug(`Print suite id ${suiteId}`)
      const runResponse = await addRun(projectId, {
        name: runName,
        description: `This run was autogenerated by the GH Action for automatic regretion.`,
        suite_id: suiteId
      })
      core.debug('Create the runId and update the match')
      core.debug(JSON.stringify(runResponse))
      match = {
        name: runResponse.name,
        id: runResponse.id
      }
    }
    return match
  } catch (error) {
    core.setFailed(error as string)
  }
}

async function getRuns(projectId: string): Promise<RunResponseInterface> {
  const config = getTestRailConfg(`get_runs/${projectId}`)
  const response = await axios.request<RunResponseInterface>(config)
  return response.data
}

async function addRun(
  projectId: string,
  runInfo: {name: string; description: string; suite_id: string}
): Promise<GetRunResponse> {
  const config = getTestRailConfg(`add_run/${projectId}`, 'POST')
  config.data = runInfo
  const runResponse = await axios.request<GetRunResponse>(config)
  return runResponse.data
}
